/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_strikerx3_jxinput_natives_XInputNatives */

#ifndef _Included_com_github_strikerx3_jxinput_natives_XInputNatives
#define _Included_com_github_strikerx3_jxinput_natives_XInputNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_strikerx3_jxinput_natives_XInputNatives
 * Method:    getLoadedLibVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_strikerx3_jxinput_natives_XInputNatives_getLoadedLibVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_github_strikerx3_jxinput_natives_XInputNatives
 * Method:    isGuideButtonSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_strikerx3_jxinput_natives_XInputNatives_isGuideButtonSupported
  (JNIEnv *, jclass);

/*
 * Class:     com_github_strikerx3_jxinput_natives_XInputNatives
 * Method:    pollDevice
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_github_strikerx3_jxinput_natives_XInputNatives_pollDevice
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_github_strikerx3_jxinput_natives_XInputNatives
 * Method:    setVibration
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_github_strikerx3_jxinput_natives_XInputNatives_setVibration
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
