/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ivan_xinput_XInputDevice */

#ifndef _Included_com_ivan_xinput_XInputDevice
#define _Included_com_ivan_xinput_XInputDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ivan_xinput_XInputDevice_MAX_PLAYERS
#define com_ivan_xinput_XInputDevice_MAX_PLAYERS 4L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_UP
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_UP 1L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_DOWN
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_DOWN 2L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_LEFT
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_LEFT 4L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_RIGHT
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_DPAD_RIGHT 8L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_START
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_START 16L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_BACK
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_BACK 32L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_LEFT_THUMB
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_LEFT_THUMB 64L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_RIGHT_THUMB
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_RIGHT_THUMB 128L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_LEFT_SHOULDER
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_LEFT_SHOULDER 256L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_RIGHT_SHOULDER
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_RIGHT_SHOULDER 512L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_A
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_A 4096L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_B
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_B 8192L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_X
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_X 16384L
#undef com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_Y
#define com_ivan_xinput_XInputDevice_XINPUT_GAMEPAD_Y -32768L
#undef com_ivan_xinput_XInputDevice_ERROR_SUCCESS
#define com_ivan_xinput_XInputDevice_ERROR_SUCCESS 0L
#undef com_ivan_xinput_XInputDevice_ERROR_DEVICE_NOT_CONNECTED
#define com_ivan_xinput_XInputDevice_ERROR_DEVICE_NOT_CONNECTED 1167L
/*
 * Class:     com_ivan_xinput_XInputDevice
 * Method:    pollDevice
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_ivan_xinput_XInputDevice_pollDevice
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_ivan_xinput_XInputDevice
 * Method:    setVibration
 * Signature: (ISS)I
 */
JNIEXPORT jint JNICALL Java_com_ivan_xinput_XInputDevice_setVibration
  (JNIEnv *, jclass, jint, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
